# Generated by Django 4.1.3 on 2022-11-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="password",
            name="ciphertext",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="ciphertext",
            field=models.CharField(max_length=256),
        ),
    ]
